#!/usr/bin/env npx ts-node
/**
 * FULL STRATEGY BACKTEST — Simulates the complete Phase 1-3 strategy
 *
 * Uses all 39,500+ real cycle observations from the VM (Jan 19 – Feb 14, 2026).
 * Models every feature we deployed:
 *   - LP repositioning when out of range (with configurable delay)
 *   - Price stabilization (defer reposition if price moving >0.5% in 30s)
 *   - Rebalance cooldown (MIN_REBALANCE_INTERVAL_MS)
 *   - Efficient delta-only swaps (swap ratio delta, not 50%)
 *   - EOD slippage cap at 200bps
 *   - Concentration scaling (APR ∝ 1/rangeWidth)
 *   - Funding cost on hedge notional
 *   - Gas costs per reposition
 *
 * Tests edge cases:
 *   - Large intraday moves (>5% in a session)
 *   - Sustained out-of-range drift
 *   - Low APR periods
 *   - Weekend gaps
 *   - Rebalance thrashing detection
 */

import * as fs from 'fs';

// ============================================================================
// Load real data
// ============================================================================
interface CycleRow {
    timestamp: number;
    tslaPrice: number;
    poolApr: number;
    poolTvl: number;
}

function loadData(): CycleRow[] {
    // Try full export first, then fallback to old format
    for (const csvPath of ['/tmp/vm_cycles_full.csv', '/tmp/vm_cycles.csv']) {
        if (!fs.existsSync(csvPath)) continue;
        const lines = fs.readFileSync(csvPath, 'utf-8').split('\n').filter(Boolean);
        const header = lines[0].split(',');
        const priceIdx = header.indexOf('tsla_price');
        const aprIdx = header.indexOf('pool_apr');
        const tvlIdx = header.indexOf('pool_tvl');
        const tsIdx = header.indexOf('timestamp');

        const rows: CycleRow[] = [];
        for (let i = 1; i < lines.length; i++) {
            const cols = lines[i].split(',');
            const tslaPrice = parseFloat(cols[priceIdx >= 0 ? priceIdx : 1]);
            const poolApr = parseFloat(cols[aprIdx >= 0 ? aprIdx : 6]);
            const poolTvl = parseFloat(cols[tvlIdx >= 0 ? tvlIdx : 7]);
            if (tslaPrice > 0) {
                rows.push({
                    timestamp: parseInt(cols[tsIdx >= 0 ? tsIdx : 0]),
                    tslaPrice,
                    poolApr: isNaN(poolApr) ? 0 : poolApr,
                    poolTvl: isNaN(poolTvl) ? 0 : poolTvl,
                });
            }
        }
        console.log(`Loaded ${rows.length} rows from ${csvPath}`);
        return rows;
    }
    console.error('ERROR: No CSV data found. Export from VM first.');
    process.exit(1);
}

// ============================================================================
// Strategy parameters
// ============================================================================
interface StrategyConfig {
    rangePercent: number;           // ±X% LP range
    positionSizeUsd: number;       // Total capital
    leverage: number;              // Hedge leverage
    maxOutOfRangeMs: number;       // How long before repositioning
    minRebalanceIntervalMs: number; // Cooldown between repositions
    priceStabilizationWindowMs: number;   // Window for stability check
    priceStabilizationMaxMove: number;    // Max % move in window (0.005 = 0.5%)
    lpSlippageBps: number;         // Slippage per swap
    swapPortionOnReposition: number; // Fraction of position swapped (efficient = ~0.15, old = 0.50)
    gasPerRepositionUsd: number;   // Gas cost per reposition
    dailyFundingRate: number;      // Daily funding rate INCOME on short hedge (shorts earn this)
    eodSlippageCapBps: number;     // Max EOD slippage
}

// Real concentration multipliers from on-chain tick data (Feb 19, 2026)
// Generated by scripts/query_liquidity_distribution.ts
// Accounts for actual liquidity distribution (other LPs also concentrate near center)
const REAL_CONCENTRATION: Record<number, number> = {
    0.005: 19.74,  // ±0.5%
    0.01: 8.20,    // ±1.0%
    0.015: 5.19,   // ±1.5%
    0.02: 3.78,    // ±2.0%
    0.03: 2.47,    // ±3.0%
    0.05: 1.67,    // ±5.0%
    0.075: 1.22,   // ±7.5%
    0.1: 1.00,     // ±10.0% (reference)
    0.15: 0.77,    // ±15.0%
    0.2: 0.65,     // ±20.0%
};

function getRealConcentration(rangePercent: number): number {
    if (REAL_CONCENTRATION[rangePercent]) return REAL_CONCENTRATION[rangePercent];
    const ranges = Object.keys(REAL_CONCENTRATION).map(Number).sort((a, b) => a - b);
    for (let i = 0; i < ranges.length - 1; i++) {
        if (rangePercent >= ranges[i] && rangePercent <= ranges[i + 1]) {
            const t = (rangePercent - ranges[i]) / (ranges[i + 1] - ranges[i]);
            return REAL_CONCENTRATION[ranges[i]] * (1 - t) + REAL_CONCENTRATION[ranges[i + 1]] * t;
        }
    }
    return 1.0;
}

// Half of capital goes to LP, half to hedge collateral
const LP_FRACTION = 0.5;

/**
 * Compute the realized cost (IL + tracking error) of a delta-hedged LP reposition.
 * Returns loss as a POSITIVE fraction of LP value.
 *
 * For delta-hedged concentrated LP, directional moves cancel via the hedge.
 * What remains is the gamma cost (IL) from the LP acting as market maker.
 * When out of range, the LP freezes (delta=0) but hedge is still short → tracking error.
 *
 * Formula derivation:
 *   V_LP(P₁) - V_hold(P₁) + hedge_PnL = L×√P₀×(2√r - r - 1)
 *   As fraction of LP value (V₀ ≈ L×√P₀×w): (2√r - r - 1) / w
 *   where r = P₁/P₀ (price ratio), w = rangePercent
 */
function computeRepositionCost(priceRatio: number, rangePercent: number): number {
    const r = priceRatio;
    const w = rangePercent;

    if (r >= 1 - w && r <= 1 + w) {
        // In range: pure concentrated IL (gamma cost)
        return -(2 * Math.sqrt(r) - r - 1) / w;
    }

    // Out of range: IL frozen at range edge + tracking error from unhedged exposure.
    // LP delta = 0 when out of range, but hedge is still short → net short exposure.
    const rEdge = r > 1 ? 1 + w : 1 - w;
    const edgeIL = -(2 * Math.sqrt(rEdge) - rEdge - 1) / w;
    const trackingError = Math.abs(r - rEdge) / 2;

    return edgeIL + trackingError;
}

const DEFAULT_CONFIG: StrategyConfig = {
    rangePercent: 0.02,             // ±2% (current deployed)
    positionSizeUsd: 14000,
    leverage: 2,
    maxOutOfRangeMs: 0,             // Immediate reposition when stable (no timer)
    minRebalanceIntervalMs: 1_800_000, // 30 min cooldown (current deployed)
    priceStabilizationWindowMs: 30_000, // 30s
    priceStabilizationMaxMove: 0.005,   // 0.5%
    lpSlippageBps: 30,
    swapPortionOnReposition: 0.15,  // Efficient: only swap ratio delta (~15%)
    gasPerRepositionUsd: 0.50,
    dailyFundingRate: 0.0006,       // 0.06%/day funding INCOME (shorts earn this)
    eodSlippageCapBps: 200,
};

// ============================================================================
// Simulation engine
// ============================================================================
interface SimResult {
    config: StrategyConfig;
    totalDays: number;
    timeInRange: number;
    repositions: number;
    repositionsDeferred: number;    // Deferred due to price instability
    cooldownSkips: number;          // Skipped due to cooldown
    grossFeesUsd: number;
    ilCostUsd: number;              // Total impermanent loss realized at repositions
    repoSlippageCostUsd: number;
    gasUsd: number;
    fundingIncomeUsd: number;
    bootstrapCostUsd: number;
    netPnlUsd: number;
    netApy: number;
    maxDrawdownPct: number;
    // Edge case stats
    largestPriceMove1h: number;     // Largest 1-hour % move
    longestOorStreak: number;       // Longest out-of-range streak (minutes)
    reposPerDay: number;
}

function simulate(data: CycleRow[], cfg: StrategyConfig): SimResult {
    const totalMs = data[data.length - 1].timestamp - data[0].timestamp;
    const totalDays = totalMs / (1000 * 60 * 60 * 24);

    // Concentration factor (from real on-chain liquidity distribution)
    const concentrationFactor = getRealConcentration(cfg.rangePercent);

    // Compute median APR for fallback
    const nonZeroAprs = data.filter(d => d.poolApr > 0).map(d => d.poolApr / 100);
    nonZeroAprs.sort((a, b) => a - b);
    const medianApr = nonZeroAprs.length > 0 ? nonZeroAprs[Math.floor(nonZeroAprs.length / 2)] : 0;

    // Position state
    let position = cfg.positionSizeUsd;
    const bootstrapCost = position * 0.5 * (cfg.lpSlippageBps / 10000);
    position -= bootstrapCost;

    let rangeCenter = data[0].tslaPrice;
    let lastRebalanceTs = 0;
    let outOfRangeSince: number | null = null;

    // Price history buffer for stabilization
    const priceBuffer: { ts: number; price: number }[] = [];

    // Stats
    let periodsInRange = 0;
    let repositions = 0;
    let repositionsDeferred = 0;
    let cooldownSkips = 0;
    let totalGrossFees = 0;
    let totalIL = 0;
    let totalRepoSlippage = 0;
    let totalGas = 0;
    let totalFunding = 0;

    let peakValue = position;
    let maxDrawdown = 0;

    // Edge case tracking
    let longestOorStreak = 0;
    let currentOorStreak = 0;
    let largestPriceMove1h = 0;

    // 1-hour price window for volatility tracking
    const hourPrices: { ts: number; price: number }[] = [];

    // Group by day for daily compounding
    const dayMs = 1000 * 60 * 60 * 24;
    const startDay = Math.floor(data[0].timestamp / dayMs);
    const endDay = Math.floor(data[data.length - 1].timestamp / dayMs);

    for (let day = startDay; day <= endDay; day++) {
        const dayStart = day * dayMs;
        const dayEnd = (day + 1) * dayMs;
        const dayData = data.filter(d => d.timestamp >= dayStart && d.timestamp < dayEnd);
        if (dayData.length === 0) continue;

        let dayPeriodsInRange = 0;
        let dayRepos = 0;
        let dayAprSum = 0;
        let dayAprCount = 0;

        for (const point of dayData) {
            const rangeLow = rangeCenter * (1 - cfg.rangePercent);
            const rangeHigh = rangeCenter * (1 + cfg.rangePercent);
            const inRange = point.tslaPrice >= rangeLow && point.tslaPrice <= rangeHigh;

            // Track price buffer for stabilization
            priceBuffer.push({ ts: point.timestamp, price: point.tslaPrice });
            const bufCutoff = point.timestamp - 120_000; // 2 min
            while (priceBuffer.length > 0 && priceBuffer[0].ts < bufCutoff) priceBuffer.shift();

            // Track 1-hour price moves
            hourPrices.push({ ts: point.timestamp, price: point.tslaPrice });
            const hourCutoff = point.timestamp - 3_600_000;
            while (hourPrices.length > 0 && hourPrices[0].ts < hourCutoff) hourPrices.shift();
            if (hourPrices.length >= 2) {
                const move = Math.abs(hourPrices[hourPrices.length - 1].price - hourPrices[0].price) / hourPrices[0].price;
                if (move > largestPriceMove1h) largestPriceMove1h = move;
            }

            if (inRange) {
                dayPeriodsInRange++;
                currentOorStreak = 0;
                if (outOfRangeSince !== null) outOfRangeSince = null;

                if (point.poolApr > 0) {
                    dayAprSum += point.poolApr / 100;
                    dayAprCount++;
                }
            } else {
                // Out of range
                currentOorStreak++;
                if (currentOorStreak > longestOorStreak) longestOorStreak = currentOorStreak;

                if (outOfRangeSince === null) {
                    outOfRangeSince = point.timestamp;
                }

                // Check if we should reposition
                const oorDuration = point.timestamp - outOfRangeSince;
                const timeSinceLastRebalance = point.timestamp - lastRebalanceTs;

                if (oorDuration >= cfg.maxOutOfRangeMs) {
                    // Check cooldown
                    if (timeSinceLastRebalance < cfg.minRebalanceIntervalMs) {
                        cooldownSkips++;
                        continue;
                    }

                    // Check price stabilization
                    const recentPrices = priceBuffer.filter(p => p.ts > point.timestamp - cfg.priceStabilizationWindowMs);
                    let stable = true;
                    if (recentPrices.length >= 2) {
                        const first = recentPrices[0].price;
                        const last = recentPrices[recentPrices.length - 1].price;
                        if (Math.abs(last - first) / first > cfg.priceStabilizationMaxMove) {
                            stable = false;
                        }
                    }

                    if (!stable) {
                        repositionsDeferred++;
                        continue;
                    }

                    // REPOSITION
                    dayRepos++;

                    // Impermanent loss: realized when closing LP at a different price than center
                    // For delta-hedged LP, directional moves cancel — IL is the residual gamma cost
                    const priceRatio = point.tslaPrice / rangeCenter;
                    const ilFraction = computeRepositionCost(priceRatio, cfg.rangePercent);
                    const ilCost = ilFraction * position * LP_FRACTION;
                    totalIL += ilCost;
                    position -= ilCost;

                    // Cost: swap only the ratio delta (not 50%)
                    const repoSlippage = cfg.swapPortionOnReposition * position * (cfg.lpSlippageBps / 10000);
                    totalRepoSlippage += repoSlippage;
                    totalGas += cfg.gasPerRepositionUsd;

                    position -= repoSlippage;
                    position -= cfg.gasPerRepositionUsd;

                    rangeCenter = point.tslaPrice;
                    outOfRangeSince = null;
                    lastRebalanceTs = point.timestamp;
                }
            }
        }

        periodsInRange += dayPeriodsInRange;
        repositions += dayRepos;

        const timeInRangeToday = dayPeriodsInRange / dayData.length;

        // Fee income (concentration-scaled, only when in range)
        const dayAvgApr = dayAprCount > 0 ? dayAprSum / dayAprCount : medianApr;
        const positionApr = dayAvgApr * concentrationFactor;
        const dailyFees = position * (positionApr / 365) * timeInRangeToday;
        totalGrossFees += dailyFees;

        // Funding INCOME (shorts earn on Flash Trade)
        const hedgeNotional = position / (1 + 1 / cfg.leverage); // LP portion, roughly
        const fundingIncome = hedgeNotional * cfg.dailyFundingRate;
        totalFunding += fundingIncome;

        // Net daily (fees + funding income)
        position += dailyFees + fundingIncome;

        // Drawdown tracking
        if (position > peakValue) peakValue = position;
        const dd = (peakValue - position) / peakValue;
        if (dd > maxDrawdown) maxDrawdown = dd;
    }

    const totalPeriods = data.length;
    const timeInRange = periodsInRange / totalPeriods;
    const netPnl = position - cfg.positionSizeUsd;
    const growthRatio = position / cfg.positionSizeUsd;
    const netApy = Math.pow(growthRatio, 365 / totalDays) - 1;

    return {
        config: cfg,
        totalDays,
        timeInRange,
        repositions,
        repositionsDeferred,
        cooldownSkips,
        grossFeesUsd: totalGrossFees,
        ilCostUsd: totalIL,
        repoSlippageCostUsd: totalRepoSlippage,
        gasUsd: totalGas,
        fundingIncomeUsd: totalFunding,
        bootstrapCostUsd: bootstrapCost,
        netPnlUsd: netPnl,
        netApy,
        maxDrawdownPct: maxDrawdown,
        largestPriceMove1h,
        longestOorStreak,
        reposPerDay: repositions / totalDays,
    };
}

// ============================================================================
// Scenario definitions
// ============================================================================
interface Scenario {
    name: string;
    overrides: Partial<StrategyConfig>;
    description: string;
}

const SCENARIOS: Scenario[] = [
    // ── Core range width sweep ──────────────────────────────────────────────
    { name: '±0.5%', overrides: { rangePercent: 0.005 }, description: 'Ultra-tight' },
    { name: '±1%', overrides: { rangePercent: 0.01 }, description: 'Tightest viable' },
    { name: '±1.5%', overrides: { rangePercent: 0.015 }, description: 'Between 1 and 2' },
    { name: '±2% (current)', overrides: { rangePercent: 0.02 }, description: 'Current deployed' },
    { name: '±3%', overrides: { rangePercent: 0.03 }, description: 'Previous deployed' },
    { name: '±5%', overrides: { rangePercent: 0.05 }, description: 'Wide range' },
    { name: '±10%', overrides: { rangePercent: 0.10 }, description: 'Very wide' },

    // ── ±1% sensitivity: what kills it? ─────────────────────────────────────
    { name: '±1% NO STAB', overrides: { rangePercent: 0.01, priceStabilizationMaxMove: 1.0 }, description: 'No stabilization at ±1%' },
    { name: '±1% STRICT', overrides: { rangePercent: 0.01, priceStabilizationMaxMove: 0.002 }, description: 'Strict stabilization at ±1%' },
    { name: '±1% 5m COOL', overrides: { rangePercent: 0.01, minRebalanceIntervalMs: 300_000 }, description: '5 min cooldown at ±1%' },
    { name: '±1% 60m COOL', overrides: { rangePercent: 0.01, minRebalanceIntervalMs: 3_600_000 }, description: '60 min cooldown at ±1%' },

    // ── ±2% sensitivity for comparison ──────────────────────────────────────
    { name: '±2% NO STAB', overrides: { rangePercent: 0.02, priceStabilizationMaxMove: 1.0 }, description: 'No stabilization at ±2%' },
    { name: '±2% 5m COOL', overrides: { rangePercent: 0.02, minRebalanceIntervalMs: 300_000 }, description: '5 min cooldown at ±2%' },

    // ── Funding sensitivity ─────────────────────────────────────────────────
    { name: '±2% 0 FUND', overrides: { dailyFundingRate: 0 }, description: 'No funding income' },
    { name: '±2% 0.1%/d', overrides: { dailyFundingRate: 0.001 }, description: 'High funding income' },

    // ── Bear market / stress scenarios ────────────────────────────────────
    { name: '±1% 0 FUND', overrides: { rangePercent: 0.01, dailyFundingRate: 0 }, description: 'No funding income at ±1%' },
    { name: '±1% NEG FUND', overrides: { rangePercent: 0.01, dailyFundingRate: -0.0003 }, description: 'Shorts pay 3bps/day (bear)' },
    { name: '±1% 2x SLIP', overrides: { rangePercent: 0.01, lpSlippageBps: 60 }, description: 'Double slippage (stressed)' },
    { name: '±1% STRESS', overrides: { rangePercent: 0.01, dailyFundingRate: 0, lpSlippageBps: 60, gasPerRepositionUsd: 1.00 }, description: 'Bear: 0 fund + 2x slip + 2x gas' },
    { name: '±0.5% STRESS', overrides: { rangePercent: 0.005, dailyFundingRate: 0, lpSlippageBps: 60, gasPerRepositionUsd: 1.00 }, description: 'Ultra-tight stress test' },

    // ── Reference: old broken strategy ──────────────────────────────────────
    { name: 'OLD (no repo)', overrides: { rangePercent: 0.05, maxOutOfRangeMs: 999_999_999_999 }, description: 'Old: ±5%, never reposition' },
];

// ============================================================================
// Main
// ============================================================================
function main() {
    const data = loadData();

    const totalMs = data[data.length - 1].timestamp - data[0].timestamp;
    const totalDays = (totalMs / (1000 * 60 * 60 * 24)).toFixed(1);
    const prices = data.map(d => d.tslaPrice).filter(p => p > 0);
    const minPrice = Math.min(...prices);
    const maxPrice = Math.max(...prices);
    const avgPrice = prices.reduce((a, b) => a + b, 0) / prices.length;
    const priceRange = ((maxPrice - minPrice) / avgPrice * 100).toFixed(1);

    const nonZeroAprs = data.filter(d => d.poolApr > 0).map(d => d.poolApr);
    nonZeroAprs.sort((a, b) => a - b);
    const p25Apr = nonZeroAprs[Math.floor(nonZeroAprs.length * 0.25)];
    const p50Apr = nonZeroAprs[Math.floor(nonZeroAprs.length * 0.50)];
    const p75Apr = nonZeroAprs[Math.floor(nonZeroAprs.length * 0.75)];
    const avgApr = nonZeroAprs.reduce((a, b) => a + b, 0) / nonZeroAprs.length;

    // Detect largest single-session moves
    const sessionPrices: { date: string; open: number; close: number; high: number; low: number }[] = [];
    let lastDate = '';
    let sessionHigh = 0, sessionLow = Infinity, sessionOpen = 0;
    for (const d of data) {
        const date = new Date(d.timestamp).toISOString().slice(0, 10);
        if (date !== lastDate) {
            if (lastDate) {
                sessionPrices.push({ date: lastDate, open: sessionOpen, close: d.tslaPrice, high: sessionHigh, low: sessionLow });
            }
            lastDate = date;
            sessionOpen = d.tslaPrice;
            sessionHigh = d.tslaPrice;
            sessionLow = d.tslaPrice;
        }
        if (d.tslaPrice > sessionHigh) sessionHigh = d.tslaPrice;
        if (d.tslaPrice < sessionLow) sessionLow = d.tslaPrice;
    }

    console.log('════════════════════════════════════════════════════════════════════════════════════════════════════');
    console.log('FULL STRATEGY BACKTEST — Phase 1-3 Validation');
    console.log('════════════════════════════════════════════════════════════════════════════════════════════════════\n');

    console.log(`Data: ${data.length} samples over ${totalDays} days`);
    console.log(`TSLA: $${minPrice.toFixed(2)} – $${maxPrice.toFixed(2)} (avg $${avgPrice.toFixed(2)}, ${priceRange}% total range)`);
    console.log(`Pool APR: P25=${p25Apr?.toFixed(1)}% | Med=${p50Apr?.toFixed(1)}% | P75=${p75Apr?.toFixed(1)}% | Mean=${avgApr?.toFixed(1)}%`);
    console.log(`Position: $${DEFAULT_CONFIG.positionSizeUsd} | Slippage: ${DEFAULT_CONFIG.lpSlippageBps}bps | Leverage: ${DEFAULT_CONFIG.leverage}x | Funding: ${(DEFAULT_CONFIG.dailyFundingRate * 100).toFixed(2)}%/day INCOME\n`);

    // Identify stress periods
    console.log('STRESS PERIODS IN DATA:');
    for (const s of sessionPrices) {
        const intradayRange = ((s.high - s.low) / s.open * 100);
        if (intradayRange > 3) {
            console.log(`  ${s.date}: $${s.low.toFixed(0)}–$${s.high.toFixed(0)} (${intradayRange.toFixed(1)}% intraday range)`);
        }
    }
    console.log('');

    // Run all scenarios
    console.log('┌──────────────────┬────────┬────────┬────────┬─────────┬─────────┬─────────┬────────┬─────────┬─────────┬─────────┬────────┐');
    console.log('│ Scenario         │ In-Rng │ Repos  │ Defer  │ Gross$  │ IL$     │ Repo$   │ Fund+$ │ Gas$    │ Net P&L │ Net APY │ MaxDD  │');
    console.log('├──────────────────┼────────┼────────┼────────┼─────────┼─────────┼─────────┼────────┼─────────┼─────────┼─────────┼────────┤');

    const results: SimResult[] = [];

    for (const scenario of SCENARIOS) {
        const cfg = { ...DEFAULT_CONFIG, ...scenario.overrides };
        const r = simulate(data, cfg);
        results.push(r);

        const marker = r.netApy >= 0.50 ? '★' :
                        r.netApy >= 0.25 ? '◆' :
                        r.netApy >= 0.10 ? '○' :
                        r.netApy >= 0    ? '·' : '✗';

        const name = scenario.name.padEnd(16);
        console.log(
            `│${marker}${name} │` +
            ` ${(r.timeInRange * 100).toFixed(1).padStart(5)}% │` +
            ` ${r.repositions.toString().padStart(5)}  │` +
            ` ${r.repositionsDeferred.toString().padStart(5)}  │` +
            ` $${r.grossFeesUsd.toFixed(0).padStart(6)} │` +
            ` $${r.ilCostUsd.toFixed(0).padStart(6)} │` +
            ` $${r.repoSlippageCostUsd.toFixed(0).padStart(6)} │` +
            ` $${r.fundingIncomeUsd.toFixed(0).padStart(5)} │` +
            ` $${r.gasUsd.toFixed(0).padStart(6)} │` +
            ` $${r.netPnlUsd.toFixed(0).padStart(6)} │` +
            ` ${(r.netApy * 100).toFixed(1).padStart(6)}% │` +
            ` ${(r.maxDrawdownPct * 100).toFixed(1).padStart(4)}% │`
        );
    }

    console.log('└──────────────────┴────────┴────────┴────────┴─────────┴─────────┴─────────┴────────┴─────────┴─────────┴─────────┴────────┘');
    console.log('★ = 50%+ APY | ◆ = 25%+ APY | ○ = 10%+ APY | · = Profitable | ✗ = Loss\n');

    // Find optimal
    const best = results.reduce((a, b) => a.netApy > b.netApy ? a : b);
    const bestScenario = SCENARIOS[results.indexOf(best)];
    const current = results.find(r => r.config.rangePercent === 0.03 &&
        r.config.swapPortionOnReposition === 0.15 &&
        r.config.dailyFundingRate === 0.0003 &&
        r.config.priceStabilizationMaxMove === 0.005 &&
        r.config.minRebalanceIntervalMs === 300_000 &&
        r.config.maxOutOfRangeMs === 3_600_000);

    console.log('════════════════════════════════════════════════════════════════════════════════════════════════════');
    console.log('ANALYSIS');
    console.log('════════════════════════════════════════════════════════════════════════════════════════════════════\n');

    console.log(`BEST SCENARIO: ${bestScenario.name}`);
    console.log(`  Net APY:       ${(best.netApy * 100).toFixed(1)}%`);
    console.log(`  Time in range: ${(best.timeInRange * 100).toFixed(1)}%`);
    console.log(`  Repos:         ${best.repositions} (${best.reposPerDay.toFixed(1)}/day)`);
    console.log(`  Deferred:      ${best.repositionsDeferred} (price too volatile)`);
    console.log(`  Max drawdown:  ${(best.maxDrawdownPct * 100).toFixed(2)}%`);
    console.log('');

    // ── HEAD-TO-HEAD: ±1% vs ±2% ──────────────────────────────────────────
    const r1pct = results.find(r => r.config.rangePercent === 0.01 &&
        r.config.priceStabilizationMaxMove === 0.005 &&
        r.config.minRebalanceIntervalMs === 1_800_000);
    const r2pct = results.find(r => r.config.rangePercent === 0.02 &&
        r.config.priceStabilizationMaxMove === 0.005 &&
        r.config.minRebalanceIntervalMs === 1_800_000);

    if (r1pct && r2pct) {
        console.log('┌─────────────────────────────────────────────────────────┐');
        console.log('│           HEAD-TO-HEAD: ±1% vs ±2% (current)           │');
        console.log('├──────────────────────┬───────────────┬─────────────────┤');
        console.log('│ Metric               │ ±1%           │ ±2% (current)   │');
        console.log('├──────────────────────┼───────────────┼─────────────────┤');
        console.log(`│ Net APY              │ ${(r1pct.netApy * 100).toFixed(1).padStart(10)}%  │ ${(r2pct.netApy * 100).toFixed(1).padStart(12)}%  │`);
        console.log(`│ Time in range        │ ${(r1pct.timeInRange * 100).toFixed(1).padStart(10)}%  │ ${(r2pct.timeInRange * 100).toFixed(1).padStart(12)}%  │`);
        console.log(`│ Repos total          │ ${r1pct.repositions.toString().padStart(11)}   │ ${r2pct.repositions.toString().padStart(13)}   │`);
        console.log(`│ Repos/day            │ ${r1pct.reposPerDay.toFixed(1).padStart(11)}   │ ${r2pct.reposPerDay.toFixed(1).padStart(13)}   │`);
        console.log(`│ Deferred (unstable)  │ ${r1pct.repositionsDeferred.toString().padStart(11)}   │ ${r2pct.repositionsDeferred.toString().padStart(13)}   │`);
        console.log(`│ Gross fees           │ $${r1pct.grossFeesUsd.toFixed(0).padStart(10)}   │ $${r2pct.grossFeesUsd.toFixed(0).padStart(12)}   │`);
        console.log(`│ Impermanent loss     │ $${r1pct.ilCostUsd.toFixed(0).padStart(10)}   │ $${r2pct.ilCostUsd.toFixed(0).padStart(12)}   │`);
        console.log(`│ Funding income       │ $${r1pct.fundingIncomeUsd.toFixed(0).padStart(10)}   │ $${r2pct.fundingIncomeUsd.toFixed(0).padStart(12)}   │`);
        console.log(`│ Repo slippage        │ $${r1pct.repoSlippageCostUsd.toFixed(0).padStart(10)}   │ $${r2pct.repoSlippageCostUsd.toFixed(0).padStart(12)}   │`);
        console.log(`│ Gas cost             │ $${r1pct.gasUsd.toFixed(0).padStart(10)}   │ $${r2pct.gasUsd.toFixed(0).padStart(12)}   │`);
        console.log(`│ Net P&L              │ $${r1pct.netPnlUsd.toFixed(0).padStart(10)}   │ $${r2pct.netPnlUsd.toFixed(0).padStart(12)}   │`);
        console.log(`│ Max drawdown         │ ${(r1pct.maxDrawdownPct * 100).toFixed(2).padStart(10)}%  │ ${(r2pct.maxDrawdownPct * 100).toFixed(2).padStart(12)}%  │`);
        console.log(`│ Longest OOR streak   │ ${r1pct.longestOorStreak.toString().padStart(8)} obs  │ ${r2pct.longestOorStreak.toString().padStart(10)} obs  │`);
        console.log('└──────────────────────┴───────────────┴─────────────────┘');

        const apyDiff = r1pct.netApy - r2pct.netApy;
        const apyRatio = r2pct.netApy > 0 ? r1pct.netApy / r2pct.netApy : Infinity;
        console.log(`\n  ±1% is ${apyDiff > 0 ? 'BETTER' : 'WORSE'} by ${(Math.abs(apyDiff) * 100).toFixed(1)}pp APY (${apyRatio.toFixed(1)}x)`);
        console.log(`  ±1% does ${r1pct.reposPerDay.toFixed(1)} repos/day vs ±2%'s ${r2pct.reposPerDay.toFixed(1)}/day (${(r1pct.reposPerDay / Math.max(r2pct.reposPerDay, 0.1)).toFixed(1)}x more)`);

        // Breakeven analysis: if X% of ±1% repositions fail (earn $0 for that period),
        // at what failure rate does ±1% lose to ±2%?
        if (r1pct.netApy > r2pct.netApy && r1pct.grossFeesUsd > 0) {
            const feeAdvantage = r1pct.grossFeesUsd - r2pct.grossFeesUsd;
            const costAdvantage = (r1pct.repoSlippageCostUsd + r1pct.gasUsd) - (r2pct.repoSlippageCostUsd + r2pct.gasUsd);
            const netAdvantage = feeAdvantage - costAdvantage;
            // Each failed repo means we lose ~(grossFees / repos) in missed fees + still pay slippage
            const feePerRepo = r1pct.grossFeesUsd / Math.max(r1pct.repositions, 1);
            const costPerRepo = (r1pct.repoSlippageCostUsd + r1pct.gasUsd) / Math.max(r1pct.repositions, 1);
            const breakeven = netAdvantage / (feePerRepo + costPerRepo) / r1pct.repositions;
            console.log(`  Breakeven failure rate: ${(breakeven * 100).toFixed(0)}% of ±1% repos can fail before ±2% wins`);
        }
        console.log('');
    }

    // ── ±1% SENSITIVITY ────────────────────────────────────────────────────
    const r1noStab = results.find(r => r.config.rangePercent === 0.01 && r.config.priceStabilizationMaxMove === 1.0);
    const r1strict = results.find(r => r.config.rangePercent === 0.01 && r.config.priceStabilizationMaxMove === 0.002);
    const r1_5mCool = results.find(r => r.config.rangePercent === 0.01 && r.config.minRebalanceIntervalMs === 300_000);
    const r1_60mCool = results.find(r => r.config.rangePercent === 0.01 && r.config.minRebalanceIntervalMs === 3_600_000);

    if (r1pct && r1noStab && r1strict && r1_5mCool && r1_60mCool) {
        console.log('±1% SENSITIVITY ANALYSIS:');
        console.log(`  Default (30m cool, 0.5% stab): ${(r1pct.netApy * 100).toFixed(1)}% APY, ${r1pct.repositions} repos (${r1pct.repositionsDeferred} deferred)`);
        console.log(`  No stabilization:              ${(r1noStab.netApy * 100).toFixed(1)}% APY, ${r1noStab.repositions} repos`);
        console.log(`  Strict stabilization (0.2%):   ${(r1strict.netApy * 100).toFixed(1)}% APY, ${r1strict.repositions} repos (${r1strict.repositionsDeferred} deferred)`);
        console.log(`  5 min cooldown:                ${(r1_5mCool.netApy * 100).toFixed(1)}% APY, ${r1_5mCool.repositions} repos`);
        console.log(`  60 min cooldown:               ${(r1_60mCool.netApy * 100).toFixed(1)}% APY, ${r1_60mCool.repositions} repos`);
        console.log('');
    }

    // ── BEAR MARKET / STRESS SCENARIOS ───────────────────────────────────
    const r1_0fund = results.find(r => r.config.rangePercent === 0.01 && r.config.dailyFundingRate === 0 && r.config.lpSlippageBps === 30);
    const r1_negFund = results.find(r => r.config.rangePercent === 0.01 && r.config.dailyFundingRate === -0.0003);
    const r1_2xSlip = results.find(r => r.config.rangePercent === 0.01 && r.config.lpSlippageBps === 60 && r.config.dailyFundingRate === 0.0006);
    const r1_stress = results.find(r => r.config.rangePercent === 0.01 && r.config.dailyFundingRate === 0 && r.config.lpSlippageBps === 60);
    const r05_stress = results.find(r => r.config.rangePercent === 0.005 && r.config.dailyFundingRate === 0 && r.config.lpSlippageBps === 60);

    if (r1pct && r1_0fund && r1_negFund && r1_2xSlip && r1_stress) {
        console.log('BEAR MARKET / STRESS SCENARIOS (±1%):');
        console.log(`  Normal (current):          ${(r1pct.netApy * 100).toFixed(1)}% APY  | Net P&L: $${r1pct.netPnlUsd.toFixed(0)}`);
        console.log(`  Zero funding:              ${(r1_0fund.netApy * 100).toFixed(1)}% APY  | Net P&L: $${r1_0fund.netPnlUsd.toFixed(0)}`);
        console.log(`  Negative funding (-3bps):  ${(r1_negFund.netApy * 100).toFixed(1)}% APY  | Net P&L: $${r1_negFund.netPnlUsd.toFixed(0)}`);
        console.log(`  Double slippage (60bps):   ${(r1_2xSlip.netApy * 100).toFixed(1)}% APY  | Net P&L: $${r1_2xSlip.netPnlUsd.toFixed(0)}`);
        console.log(`  Full stress (all above):   ${(r1_stress.netApy * 100).toFixed(1)}% APY  | Net P&L: $${r1_stress.netPnlUsd.toFixed(0)}`);
        if (r05_stress) {
            console.log(`  ±0.5% stress:              ${(r05_stress.netApy * 100).toFixed(1)}% APY  | Net P&L: $${r05_stress.netPnlUsd.toFixed(0)}`);
        }

        // Identify breakeven funding rate at ±1% (linear interpolation)
        if (r1_0fund.netApy < 0 && r1pct.netApy > 0) {
            const breakeven = 0.0006 * (-r1_0fund.netApy) / (r1pct.netApy - r1_0fund.netApy);
            console.log(`\n  Breakeven funding rate: ${(breakeven * 100).toFixed(3)}%/day (below this, ±1% loses money)`);
        } else if (r1_0fund.netApy >= 0) {
            console.log(`\n  ±1% is profitable EVEN with zero funding — fee income alone covers IL`);
        }
        console.log('');
    }

    // ── FUNDING SENSITIVITY ────────────────────────────────────────────────
    const noFund = results.find(r => r.config.dailyFundingRate === 0 && r.config.rangePercent === 0.02);
    const highFund = results.find(r => r.config.dailyFundingRate === 0.001 && r.config.rangePercent === 0.02);
    if (r1pct && r1_0fund && r2pct && noFund) {
        console.log('FUNDING INCOME SENSITIVITY:');
        console.log('  ±1% range:');
        console.log(`    0 bps/day:   ${(r1_0fund.netApy * 100).toFixed(1)}% APY`);
        console.log(`    6 bps/day:   ${(r1pct.netApy * 100).toFixed(1)}% APY`);
        console.log('  ±2% range:');
        console.log(`    0 bps/day:   ${(noFund.netApy * 100).toFixed(1)}% APY`);
        console.log(`    6 bps/day:   ${(r2pct.netApy * 100).toFixed(1)}% APY`);
        if (highFund) console.log(`    10 bps/day:  ${(highFund.netApy * 100).toFixed(1)}% APY`);
        console.log('');
    } else if (noFund && r2pct && highFund) {
        console.log('FUNDING INCOME SENSITIVITY (±2%):');
        console.log(`  0 bps/day (no funding):   ${(noFund.netApy * 100).toFixed(1)}% APY`);
        console.log(`  6 bps/day (current):      ${(r2pct.netApy * 100).toFixed(1)}% APY`);
        console.log(`  10 bps/day (high):        ${(highFund.netApy * 100).toFixed(1)}% APY`);
        console.log('');
    }

    // ── EDGE CASES ─────────────────────────────────────────────────────────
    const currentResult = r2pct || best;
    console.log('EDGE CASE ANALYSIS:');
    console.log(`  Largest 1h price move:  ${(currentResult.largestPriceMove1h * 100).toFixed(2)}%`);
    console.log(`  Longest OOR streak:     ${currentResult.longestOorStreak} observations (~${(currentResult.longestOorStreak * 10 / 60).toFixed(0)} min)`);

    // Compare with old broken strategy
    const old = results.find(r => r.config.maxOutOfRangeMs > 999_999_999);
    if (old) {
        console.log(`\nOLD STRATEGY (±5%, no repositioning):`);
        console.log(`  Net APY:       ${(old.netApy * 100).toFixed(1)}% ${old.netApy < 0 ? '(LOSS!)' : ''}`);
        console.log(`  Time in range: ${(old.timeInRange * 100).toFixed(1)}%`);
    }

    console.log('\n════════════════════════════════════════════════════════════════════════════════════════════════════');
    console.log('RECOMMENDATION');
    console.log('════════════════════════════════════════════════════════════════════════════════════════════════════\n');

    if (r1pct && r2pct) {
        // Rank all core scenarios by APY
        const coreResults = results.filter(r =>
            [0.005, 0.01, 0.015, 0.02, 0.03, 0.05, 0.10].includes(r.config.rangePercent) &&
            r.config.priceStabilizationMaxMove === 0.005 &&
            r.config.minRebalanceIntervalMs === 1_800_000 &&
            r.config.dailyFundingRate === 0.0006 &&
            r.config.lpSlippageBps === 30 &&
            r.config.gasPerRepositionUsd === 0.50 &&
            r.config.maxOutOfRangeMs < 999_999_999
        );
        coreResults.sort((a, b) => b.netApy - a.netApy);

        console.log('RANGE WIDTH RANKING (by Net APY with IL):');
        for (const cr of coreResults) {
            const pct = (cr.config.rangePercent * 100).toFixed(1);
            const status = cr.netApy > 0 ? 'PROFIT' : 'LOSS';
            const ilPerRepo = cr.repositions > 0 ? (cr.ilCostUsd / cr.repositions).toFixed(0) : 'N/A';
            console.log(`  ±${pct}%: ${(cr.netApy * 100).toFixed(1)}% APY (${status}) | Fees: $${cr.grossFeesUsd.toFixed(0)} - IL: $${cr.ilCostUsd.toFixed(0)} | IL/repo: $${ilPerRepo}`);
        }

        const bestCore = coreResults[0];
        const bestPct = (bestCore.config.rangePercent * 100).toFixed(1);
        console.log(`\nBEST RANGE: ±${bestPct}% at ${(bestCore.netApy * 100).toFixed(1)}% APY`);

        if (r1pct.netApy > 0 && r2pct.netApy <= 0) {
            console.log(`±1% is profitable (${(r1pct.netApy * 100).toFixed(0)}% APY), ±2% is losing money (${(r2pct.netApy * 100).toFixed(0)}% APY). ±1% is the clear winner.`);
        } else if (r1pct.netApy > r2pct.netApy) {
            const diff = ((r1pct.netApy - r2pct.netApy) * 100).toFixed(0);
            console.log(`±1% beats ±2% by ${diff}pp APY (${(r1pct.netApy * 100).toFixed(0)}% vs ${(r2pct.netApy * 100).toFixed(0)}%)`);
        } else {
            console.log(`±2% beats ±1% (${(r2pct.netApy * 100).toFixed(0)}% vs ${(r1pct.netApy * 100).toFixed(0)}%)`);
        }

        console.log(`\nKey insight: IL is ${(r1pct.ilCostUsd / r1pct.grossFeesUsd * 100).toFixed(0)}% of gross fees at ±1%, ${(r2pct.ilCostUsd / r2pct.grossFeesUsd * 100).toFixed(0)}% at ±2%`);
        console.log(`When IL ≥ fees, the strategy loses money regardless of other income.`);
    }
}

main();
